'use client';
import { useQuery } from '@tanstack/react-query';
import { api } from '../../../../lib/api';
import { Card, Pill } from '../../../../components/ui';
import Link from 'next/link';

type Message = { id: string; channel: string; messageType: string; destination: string; body: string; status: 'queued' | 'sent' | 'failed' | 'cancelled'; scheduledFor: string; sentAt: string | null; errorMessage: string | null; clientName: string | null };

export default function CommunicationsPage({ params }: { params: { locationId: string } }) {
  const settings = useQuery({ queryKey: ['settings', 'communication-settings'], queryFn: () => api.get<{ enabled: boolean }>('/settings/communication-settings') });
  const messages = useQuery({ queryKey: ['communications'], queryFn: () => api.get<Message[]>('/communications') });
  if (settings.data?.enabled === false) return <div className="mx-auto max-w-2xl pt-10"><Card className="border-[#ddd7ca] bg-white/70 p-8 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-full bg-[#e7eee9] text-xl text-[#315c4f]">✉</div><p className="mt-5 text-[11px] font-semibold uppercase tracking-[0.16em] text-[#8b6f47]">Optional feature</p><h1 className="mt-1 font-serif text-3xl font-medium">Messages are turned off</h1><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-gray-500">Customer confirmations and reminders stay hidden—and do not generate messaging costs—until an owner enables them.</p><Link href={`/locations/${params.locationId}/settings`} className="mt-5 inline-flex rounded-xl bg-[#315c4f] px-4 py-2 text-sm font-medium text-white shadow-sm">Review messaging settings</Link></Card></div>;
  const rows = messages.data ?? [];
  const queued = rows.filter((row) => row.status === 'queued').length;
  const failed = rows.filter((row) => row.status === 'failed').length;
  return <div className="space-y-5"><div><p className="mb-1 text-[11px] font-semibold uppercase tracking-[0.16em] text-[#8b6f47]">Stay connected</p><h1 className="text-3xl font-semibold tracking-tight">Messages</h1><p className="mt-1 text-sm text-gray-500">Review customer messages, delivery status, and anything that needs attention.</p></div><div className="flex gap-2"><Pill tone={queued ? 'amber' : 'green'}>{queued} queued</Pill>{failed > 0 && <Pill tone="red">{failed} failed</Pill>}</div><Card className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-black/10 text-left text-gray-500"><th className="px-4 py-3 font-medium">When</th><th className="px-4 py-3 font-medium">Client</th><th className="px-4 py-3 font-medium">Message</th><th className="px-4 py-3 font-medium">Channel</th><th className="px-4 py-3 font-medium">Status</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id} className="border-b border-black/5 align-top"><td className="whitespace-nowrap px-4 py-3">{new Date(row.scheduledFor).toLocaleString([], { dateStyle: 'short', timeStyle: 'short' })}</td><td className="px-4 py-3">{row.clientName ?? row.destination}</td><td className="max-w-xl px-4 py-3"><strong className="block capitalize">{row.messageType.replaceAll('_', ' ')}</strong><span className="text-gray-500">{row.body}</span>{row.errorMessage && <span className="block text-red-600">{row.errorMessage}</span>}</td><td className="px-4 py-3 uppercase">{row.channel}</td><td className="px-4 py-3"><Pill tone={row.status === 'failed' ? 'red' : row.status === 'queued' ? 'amber' : 'green'}>{row.status}</Pill></td></tr>)}{rows.length === 0 && <tr><td colSpan={5} className="px-4 py-10 text-center text-gray-400">No customer messages yet. Confirmations and reminders will appear here when they are created.</td></tr>}</tbody></table></Card><p className="text-xs text-gray-500">Queued messages are waiting to be sent. Delivery begins after a messaging provider is connected.</p></div>;
}
